apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-simplecrud-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-simplecrud
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-simplecrud
    spec:
      containers:
        - name: spring-boot-simplecrud
          image: simplecrud # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2500 # The port that the container is running on in the cluster